### ISSUE TITLE
Allow specifying a mode for templates 

### ISSUE THREAD

**Issue by Laevos** [cerner/cerner_tomcat#13] opened 2016-05-12 19:17 UTC
Currently, there's no clean way inside of cerner_tomcat to specify the mode that a file from a template should be created with, forcing the user to either accept the default mode of 750 or use a `file` block to manually set the created file's mode later in the recipe.

**Comment by bbaugher** [comment] 2016-10-07 21:50
This is duplicate of #4

**Closed as completed by bbaugher** 2016-10-07 21:50 UTC

**Comment by cchesser** [comment] 2017-01-03 22:59
Was this actually duplicated in #4? It appears in the [3.0.0](https://github.com/cerner/cerner_tomcat/releases/tag/v3.0.0) version of the cookbook, which includes #4 changes, it doesn't allow you to specify, and rather sets the permissions to `600` (which was previously `750`). If so, I can submit a PR to update the README to further clarify how to set this, but wasn't seeing examples, or documentation on how to control this (as this changes from the 2.x -> 3.x behavior).

**Comment by cchesser** [comment] 2017-01-03 23:09
To clarify, seeing `600` on files being managed for resources used with template (ex. landing in `conf`) and seeing `644` for remote files landing in the `lib` directory.
